Hw10
Merkald/internet.shop pull request #18
Opened 2020-05-08 11:03 UTC by Merkald

Інжектор викидує помилку через те що є 2 імплементації Дао

2020-05-08 13:50 UTC, Sofasmile commented on src/main/java/internet/shop/dao/jdbcimpl/ProductDaoJdbcImpl.java
> +        String query = "UPDATE `internet_shop`.`products` "
```suggestion
        String query = "UPDATE internet_shop.products "
```
everywhere

2020-05-08 13:50 UTC, Sofasmile commented on src/main/java/internet/shop/dao/jdbcimpl/ProductDaoJdbcImpl.java
> +                + "WHERE (`product_id` = ?);";
```suggestion
                + "WHERE product_id = ?;";
```

2020-05-08 13:50 UTC, Sofasmile commented on src/main/java/internet/shop/dao/jdbcimpl/ProductDaoJdbcImpl.java
> +            int id = statement.executeUpdate();
що повертає executeUpdate()?
Давай діставати ід за допомогою наступного коду:
```
ResultSet rs = statement.getGeneratedKeys();
            while (rs.next()) {
                Long bucketId = rs.getLong(1);
                bucket.setId(bucketId);
            }
```

2020-05-08 13:50 UTC, Sofasmile commented on src/main/java/internet/shop/dao/jdbcimpl/ProductDaoJdbcImpl.java
> +            Optional<Product> result = Optional.empty();
чи можемо ми обгортати об'єкт в обгортку перед тим як повертати результат?

2020-05-08 13:50 UTC, Sofasmile commented on src/main/java/internet/shop/dao/jdbcimpl/ProductDaoJdbcImpl.java
> +                long productId = resultSet.getLong("product_id");
довай юзати обгортку для ід?

2020-05-08 13:50 UTC, Sofasmile commented on src/main/java/internet/shop/dao/jdbcimpl/ProductDaoJdbcImpl.java
> +        return new ArrayList<>();
круто що не повертаєш null 👍

2020-05-08 13:50 UTC, Sofasmile commented on src/main/java/internet/shop/dao/jdbcimpl/ProductDaoJdbcImpl.java
> +            ex.printStackTrace();
давай створимо свій кастомний ексепшин)

2020-05-08 14:06 UTC, Merkald commented on src/main/java/internet/shop/dao/jdbcimpl/ProductDaoJdbcImpl.java
> +                long productId = resultSet.getLong("product_id");
ID поле в SQL not null

2020-05-10 11:36 UTC, boroda4436 commented on src/main/java/internet/shop/dao/jdbcimpl/ProductDaoJdbcImpl.java
> +    private static final int ID_COLUMN = 1;
nope. Please use column name, instead of column position

2020-05-10 11:37 UTC, boroda4436 requested changes

2020-05-10 11:37 UTC, boroda4436 commented on src/main/java/internet/shop/dao/jdbcimpl/ProductDaoJdbcImpl.java
> +                String productName = resultSet.getString("product_name");
code duplication on line 97

2020-05-10 17:17 UTC, Merkald commented on src/main/java/internet/shop/dao/jdbcimpl/ProductDaoJdbcImpl.java
> +    private static final int ID_COLUMN = 1;
Я писав про це в SQL є якась бага (якщо використовую імя то отримую помилку в цій частині коду тому довелось замінити на номер)

2020-05-10 17:18 UTC, Merkald commented on src/main/java/internet/shop/dao/jdbcimpl/ProductDaoJdbcImpl.java
> +    private static final int ID_COLUMN = 1;
![image](https://user-images.githubusercontent.com/26797641/81505897-66f4fe80-92fb-11ea-8169-54c62b74b575.png)

2020-05-11 07:29 UTC, boroda4436 commented on src/main/java/internet/shop/dao/jdbcimpl/ProductDaoJdbcImpl.java
> +    private static final int ID_COLUMN = 1;
Судячи з скріншоту - в тебе проблема з інжектором

2020-05-11 07:32 UTC, boroda4436 requested changes

2020-05-11 07:32 UTC, boroda4436 commented on src/main/java/internet/shop/dao/jdbcimpl/ProductDaoJdbcImpl.java
> +                Long productId = resultSet.getLong(ID_COLUMN);
тут гуд. тут можна використовувати 1

2020-05-11 07:32 UTC, boroda4436 commented on src/main/java/internet/shop/dao/jdbcimpl/ProductDaoJdbcImpl.java
> +            return Optional.of(getProductFromResultSet(resultSet).get(0));
погана практика повертати .get(0). Може скластися враження, що ти втрачаєш дані, які є у масиві

2020-05-12 08:46 UTC, dmytro-hryhoruk approved these changes

2020-05-12 08:46 UTC, dmytro-hryhoruk commented on src/main/java/internet/shop/dao/jdbcimpl/ProductDaoJdbcImpl.java
> +            throw new DataProcessingException("Cant INSERT product IN mySQL");
your exception will be logged anyway

2020-05-12 08:46 UTC, dmytro-hryhoruk commented on src/main/java/internet/shop/dao/jdbcimpl/ProductDaoJdbcImpl.java
> +    public List<Product> getProductFromResultSet(ResultSet resultSet) throws SQLException {
```suggestion
    public List<Product> getProductsFromResultSet(ResultSet resultSet) throws SQLException {
```

2020-05-12 10:16 UTC, merged